# Generated by Django 6.0.7 on 2026-08-20 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anticipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ej. ANT-2026-00126", max_length=30, unique=True
                    ),
                ),
                ("fecha", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("concepto", models.TextField(blank=True)),
                ("proyecto", models.CharField(blank=True, max_length=120)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anticipos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anticipos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("excel", "Excel de legalización"),
                            ("pdf", "PDF de facturas / recibos"),
                            ("correo", "Correo"),
                            ("otro", "Otro soporte"),
                        ],
                        default="otro",
                        max_length=10,
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos/%Y/%m/")),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "anticipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="app_applus.anticipo",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-subido_en"],
            },
        ),
        migrations.CreateModel(
            name="Legalizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ej. LEG-2026-00079", max_length=30, unique=True
                    ),
                ),
                ("fecha_presentado", models.DateField()),
                (
                    "valor_presentado",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("revision", "En espera de respuesta de SALT"),
                            ("aprobada", "Aprobada (todo reconocido)"),
                            ("parcial", "Aprobada parcialmente"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="revision",
                        max_length=20,
                    ),
                ),
                (
                    "valor_reconocido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "motivo_devolucion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soporte", "Factura no válida / soporte incompleto"),
                            ("cuenta", "Cuenta bancaria inconsistente"),
                            ("concepto", "Concepto no corresponde al anticipo"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_resultado", models.DateField(blank=True, null=True)),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("manual", "Registro manual"),
                            ("outlook", "Detectado en Outlook"),
                            ("gmail", "Detectado en Gmail"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "mensaje_id_correo",
                    models.CharField(
                        blank=True,
                        help_text="ID del correo (Outlook/Gmail) que originó este registro, si aplica.",
                        max_length=255,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anticipo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legalizacion",
                        to="app_applus.anticipo",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_presentado"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("TRABAJADOR", "Trabajador"),
                            ("SUPERVISOR", "Supervisor"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        default="TRABAJADOR",
                        max_length=20,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor asignado a este trabajador (si aplica).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reclamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("factura", models.CharField(blank=True, max_length=60)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierto", "Abierto"), ("resuelto", "Resuelto")],
                        default="abierto",
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "legalizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamos",
                        to="app_applus.legalizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
